import {Dimensions, StyleSheet} from 'react-native';
const {width, height} = Dimensions.get('screen');
const styles = StyleSheet.create({
  whole_container: {
    backgroundColor: 'black',
  },
  fltst_height: {
    height: height * 0.13,
    right: 0,
  },
  horizontal_flatLst: {
    borderRadius: 40,
    height: height * 0.08,
    width: height * 0.08,
    borderWidth: 2,
    marginHorizontal: width * 0.03,
    paddingVertical: width * 0.01,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#171717',
  },
  deflt_bordr_colr: {
    borderColor: '#171817',
  },
  changed_bordr_color: {borderColor: 'deeppink'},
  Specials: {
    color: 'white',
    left: 0,
    marginVertical: height * 0.015,
    fontSize: 18,
  },
  hori_flatlst_Image: {
    borderRadius: 40,
    height: height * 0.04,
    width: height * 0.04,
  },
  ScrollView: {height: '100%', backgroundColor: 'black'},
  deflt_small_circle: {
    position: 'absolute',
    width: width * 0.02,
    height: width * 0.02,
    alignSelf: 'flex-end',
    backgroundColor: 'lightgreen',
    top: -height * 0.01,
    left: width * 0.1,
    borderRadius: 40,
  },
  deflt_large_circle: {
    position: 'absolute',
    width: width * 0.06,
    height: width * 0.06,
    alignSelf: 'flex-end',
    backgroundColor: 'deeppink',
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    top: -height * 0.02,
    left: width * 0.07,
  },
  lf_rt_padding: {paddingLeft: 0, paddingRight: 0},
  underline: {
    backgroundColor: 'grey',
    marginRight: width * 0.03,
    marginLeft: width * 0.03,
    marginRight: width * 0.03,
    height: height * 0.003,
    marginVertical: height * 0.0011,
  },

  addmore_Text: {
    color: 'white',
    position: 'absolute',
    right: 0,
    paddingRight: width * 0.03,
    marginVertical: height * 0.025,
    fontSize: 18,
  },
  channel_Text: {
    color: 'white',
    position: 'absolute',
    left: -5,
    paddingLeft: width * 0.03,
    marginVertical: height * 0.03,
    fontSize: 18,
  },
  outer_view_container: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: width * 0.02,
    left: 0,
    marginVertical: height * 0.06,
  },
  inner_view_container: {
    width: width * 0.28,
    backgroundColor: '#171717',
    height: width * 0.28,
    left: 0,
    borderWidth: 1,
    borderRadius: 8,
    marginVertical: width * 0.02,
    alignItems: 'flex-start',
    marginHorizontal: width * 0.02,
    paddingVertical: height * 0.004,
    paddingHorizontal: width * 0.01,
    flexWrap: 'wrap',
  },
  container_image: {
    borderRadius: 40,
    height: height * 0.04,
    width: height * 0.04,
  },
  container_icon: {
    position: 'absolute',
    right: width * 0.03,
    top: height * 0.01,
    alignSelf: 'flex-end',
    width: width / 20,
  },
  container_text: {
    fontSize: width / 27,
    width: '100%',
    color: 'white',
    alignSelf: 'center',
    top: height * 0.025,
    marginHorizontal: width * 0.01,
    flexWrap: 'wrap',
    flexDirection: 'column',
  },
});
export default styles;
